<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Tfs.Portfolio.UnitTests</AssemblyName>
    <RootNamespace>Tfs.Portfolio.UnitTests</RootNamespace>
    <IsTestProject>true</IsTestProject>
    <NoWarn>$(NoWarn);NU1903;NU1603</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Core\Domain\Tfs.Portfolio.Domain.csproj" />
    <ProjectReference Include="..\..\src\Core\Application\Tfs.Portfolio.Application.csproj" />
    <PackageReference Include="xunit" Version="2.9.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
    <PackageReference Include="Moq" Version="4.20.70" />
    <PackageReference Include="Bogus" Version="35.6.0" />
    <PackageReference Include="FluentAssertions" Version="6.12.0" />
    <PackageReference Include="AutoFixture" Version="4.18.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.10.0" />
  </ItemGroup>
</Project>